version: '2'
services:
    hackathon-app:
        image: hackathon
        external_links:
            - hackathon-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/hackathon
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hackathon-postgresql:
        extends:
            file: postgresql.yml
            service: hackathon-postgresql
